### ISSUE TITLE
Misses make you lose more health or kill you instantly in 90 degree custom maps.

### ISSUE THREAD

**Issue by khiral** [kOFReadie/BSDataPuller#11]
https://streamable.com/1g7o1j
See at 0:45 I play 100$ bills 90 degree, where misses take off 15 health as expected, then after I play a custom where missing the first two blocks fails me instantly.
Removing DataPuller from my Plugins folder fixed the issue, and adding it back caused it to reappear.
Error Log
`[DEBUG @ 01:31:37 | SiraUtil] Installing: SiraInstaller (SiraUtil)
[DEBUG @ 01:31:37 | SiraUtil] Installing: HsvAppInstaller (HitScoreVisualizer)
[DEBUG @ 01:31:37 | SiraUtil] Installing: AppInstaller (SaberFactory)
[DEBUG @ 01:31:37 | SiraUtil] Installing: CustomNotesCoreInstaller (Custom Notes)
[DEBUG @ 01:31:37 | SiraUtil] Installing: CoreInstaller (Counters+)
[DEBUG @ 01:31:44 | SiraUtil] Installing: SiraMenuInstaller (SiraUtil)
[DEBUG @ 01:31:44 | SiraUtil] Installing: HsvMenuInstaller (HitScoreVisualizer)
[DEBUG @ 01:31:44 | SiraUtil] Installing: MenuInstaller (SaberFactory)
[DEBUG @ 01:31:44 | SiraUtil] Installing: CustomNotesMenuInstaller (Custom Notes)
[DEBUG @ 01:31:44 | SiraUtil] Installing: MenuUIInstaller (Counters+)
[DEBUG @ 01:31:44 | SiraUtil] Installing: PlaylistViewInstaller (PlaylistManager)
[DEBUG @ 01:32:08 | SiraUtil] Installing: SiraSaberInstaller (SiraUtil)
[DEBUG @ 01:32:08 | SiraUtil] Installing: GameInstaller (SaberFactory)
[DEBUG @ 01:32:08 | SiraUtil] Installing: CustomNotesGameInstaller (Custom Notes)
[DEBUG @ 01:32:08 | SiraUtil] Installing: ClientInstaller (DataPuller)
[DEBUG @ 01:32:08 | SiraUtil] Installing: SiraSaberEffectInstaller (SiraUtil)
[DEBUG @ 01:32:08 | SiraUtil] Installing: SiraGameLevelInstaller (SiraUtil)
[DEBUG @ 01:32:08 | SiraUtil] Installing: SiraGameInstaller (SiraUtil)
[DEBUG @ 01:32:08 | SiraUtil] Installing: IntroSkipGameInstaller (IntroSkip)
[DEBUG @ 01:32:08 | SiraUtil] Installing: HsvGameInstaller (HitScoreVisualizer)
[DEBUG @ 01:32:08 | SiraUtil] Installing: CountersInstaller (Counters+)
[CRITICAL @ 01:32:08 | SiraUtil] Error occurred while initializing IInitializable with type 'DataPuller.Client.MapEvents'
[CRITICAL @ 01:32:08 | SiraUtil] System.ArgumentException: Requested value '90Degree' was not found.
[CRITICAL @ 01:32:08 | SiraUtil]   at System.Enum+EnumResult.SetFailure (System.Enum+ParseFailureKind failure, System.String failureMessageID, System.Object failureMessageFormatArgument) [0x00023] in <9577ac7a62ef43179789031239ba8798>:0 
[CRITICAL @ 01:32:08 | SiraUtil]   at System.Enum.TryParseEnum (System.Type enumType, System.String value, System.Boolean ignoreCase, System.Enum+EnumResult& parseResult) [0x0017a] in <9577ac7a62ef43179789031239ba8798>:0 
[CRITICAL @ 01:32:08 | SiraUtil]   at System.Enum.Parse (System.Type enumType, System.String value, System.Boolean ignoreCase) [0x00010] in <9577ac7a62ef43179789031239ba8798>:0 
[CRITICAL @ 01:32:08 | SiraUtil]   at System.Enum.Parse (System.Type enumType, System.String value) [0x00000] in <9577ac7a62ef43179789031239ba8798>:0 
[CRITICAL @ 01:32:08 | SiraUtil]   at DataPuller.Client.MapEvents.SetupMapDataAndMisc () [0x00223] in <db6dbc2d93ab49c5a5bfa6283cdd6c23>:0 
[CRITICAL @ 01:32:08 | SiraUtil]   at DataPuller.Client.MapEvents.Initialize () [0x001f2] in <db6dbc2d93ab49c5a5bfa6283cdd6c23>:0 
[CRITICAL @ 01:32:08 | SiraUtil]   at (wrapper dynamic-method) Zenject.InitializableManager.Zenject.InitializableManager.Initialize_Patch0(Zenject.InitializableManager)
[WARNING @ 01:32:08 | SiraUtil] Please tell kOF.Readie to fix this!
[WARNING @ 01:32:08 | SiraUtil] Please tell kOF.Readie to fix this!
[WARNING @ 01:32:08 | SiraUtil] Please tell kOF.Readie to fix this!
[WARNING @ 01:32:08 | SiraUtil] Please tell kOF.Readie to fix this!
[WARNING @ 01:32:08 | SiraUtil] Please tell kOF.Readie to fix this!
[WARNING @ 01:32:08 | SiraUtil] Please tell kOF.Readie to fix this!
[WARNING @ 01:32:08 | SiraUtil] Please tell kOF.Readie to fix this!
[WARNING @ 01:32:08 | SiraUtil] Please tell kOF.Readie to fix this!
[WARNING @ 01:32:08 | SiraUtil] Please tell kOF.Readie to fix this!
[WARNING @ 01:32:08 | SiraUtil] Please tell kOF.Readie to fix this!
[DEBUG @ 01:33:05 | SiraUtil] Installing: SiraSaberInstaller (SiraUtil)
[DEBUG @ 01:33:05 | SiraUtil] Installing: GameInstaller (SaberFactory)
[DEBUG @ 01:33:05 | SiraUtil] Installing: CustomNotesGameInstaller (Custom Notes)
[DEBUG @ 01:33:05 | SiraUtil] Installing: ClientInstaller (DataPuller)
[DEBUG @ 01:33:05 | SiraUtil] Installing: SiraSaberEffectInstaller (SiraUtil)
[DEBUG @ 01:33:05 | SiraUtil] Installing: SiraGameLevelInstaller (SiraUtil)
[DEBUG @ 01:33:05 | SiraUtil] Installing: SiraGameInstaller (SiraUtil)
[DEBUG @ 01:33:05 | SiraUtil] Installing: IntroSkipGameInstaller (IntroSkip)
[DEBUG @ 01:33:05 | SiraUtil] Installing: HsvGameInstaller (HitScoreVisualizer)
[DEBUG @ 01:33:05 | SiraUtil] Installing: CountersInstaller (Counters+)
[DEBUG @ 01:33:29 | SiraUtil] Installing: SiraSaberInstaller (SiraUtil)
[DEBUG @ 01:33:29 | SiraUtil] Installing: GameInstaller (SaberFactory)
[DEBUG @ 01:33:29 | SiraUtil] Installing: CustomNotesGameInstaller (Custom Notes)
[DEBUG @ 01:33:29 | SiraUtil] Installing: ClientInstaller (DataPuller)
[DEBUG @ 01:33:30 | SiraUtil] Installing: SiraSaberEffectInstaller (SiraUtil)
[DEBUG @ 01:33:30 | SiraUtil] Installing: SiraGameLevelInstaller (SiraUtil)
[DEBUG @ 01:33:30 | SiraUtil] Installing: SiraGameInstaller (SiraUtil)
[DEBUG @ 01:33:30 | SiraUtil] Installing: IntroSkipGameInstaller (IntroSkip)
[DEBUG @ 01:33:30 | SiraUtil] Installing: HsvGameInstaller (HitScoreVisualizer)
[DEBUG @ 01:33:30 | SiraUtil] Installing: CountersInstaller (Counters+)
[CRITICAL @ 01:33:30 | SiraUtil] Error occurred while initializing IInitializable with type 'DataPuller.Client.MapEvents'
[CRITICAL @ 01:33:30 | SiraUtil] System.ArgumentException: Requested value '90Degree' was not found.
[CRITICAL @ 01:33:30 | SiraUtil]   at System.Enum+EnumResult.SetFailure (System.Enum+ParseFailureKind failure, System.String failureMessageID, System.Object failureMessageFormatArgument) [0x00023] in <9577ac7a62ef43179789031239ba8798>:0 
[CRITICAL @ 01:33:30 | SiraUtil]   at System.Enum.TryParseEnum (System.Type enumType, System.String value, System.Boolean ignoreCase, System.Enum+EnumResult& parseResult) [0x0017a] in <9577ac7a62ef43179789031239ba8798>:0 
[CRITICAL @ 01:33:30 | SiraUtil]   at System.Enum.Parse (System.Type enumType, System.String value, System.Boolean ignoreCase) [0x00010] in <9577ac7a62ef43179789031239ba8798>:0 
[CRITICAL @ 01:33:30 | SiraUtil]   at System.Enum.Parse (System.Type enumType, System.String value) [0x00000] in <9577ac7a62ef43179789031239ba8798>:0 
[CRITICAL @ 01:33:30 | SiraUtil]   at DataPuller.Client.MapEvents.SetupMapDataAndMisc () [0x00223] in <db6dbc2d93ab49c5a5bfa6283cdd6c23>:0 
[CRITICAL @ 01:33:30 | SiraUtil]   at DataPuller.Client.MapEvents.Initialize () [0x001f2] in <db6dbc2d93ab49c5a5bfa6283cdd6c23>:0 
[CRITICAL @ 01:33:30 | SiraUtil]   at (wrapper dynamic-method) Zenject.InitializableManager.Zenject.InitializableManager.Initialize_Patch0(Zenject.InitializableManager)
[WARNING @ 01:33:30 | SiraUtil] Please tell kOF.Readie to fix this!
[WARNING @ 01:33:30 | SiraUtil] Please tell kOF.Readie to fix this!
[WARNING @ 01:33:30 | SiraUtil] Please tell kOF.Readie to fix this!
[WARNING @ 01:33:30 | SiraUtil] Please tell kOF.Readie to fix this!
[WARNING @ 01:33:30 | SiraUtil] Please tell kOF.Readie to fix this!
[WARNING @ 01:33:30 | SiraUtil] Please tell kOF.Readie to fix this!
[WARNING @ 01:33:30 | SiraUtil] Please tell kOF.Readie to fix this!
[WARNING @ 01:33:30 | SiraUtil] Please tell kOF.Readie to fix this!
[WARNING @ 01:33:30 | SiraUtil] Please tell kOF.Readie to fix this!
[WARNING @ 01:33:30 | SiraUtil] Please tell kOF.Readie to fix this!`

**Comment by kOFReadie** [comment]
Ah, this problem again. This time by the looks of things due to it not finding the right map type. I'll look into it.

**Comment by kOFReadie** [comment]
Should be fixed with the release that should be coming out soon (later today I hope).

**Comment by FEFELAND** [comment]
Hi there. I see this issue is marked as closed but.. this is still happening on 2.0.4.0. Only does it in custom maps, not OSTs.
Thanks in advanced if you're able to look into it :D
![bug](https://user-images.githubusercontent.com/57236015/125844552-8ed0be6b-1eb8-4cc0-8eaf-50fd51f2576e.gif)

**Comment by kOFReadie** [comment]
Yeah I'll take a look into it again when i get around to it. Been out of things a lot recently so development has been very slow.

**Comment by kOFReadie** [comment]
From my testing I am pretty sure I have fixed this for good now.
The issue was that the serialized map type for 360 and 90 was `Degree360/90` but the enum is was not the same, anyway its fixed now so it should be all good.
